### ISSUE TITLE
No time zone found with key local. Fallback to UTC

### ISSUE THREAD

**Issue by tebra-jl** [maxlaverse/home-assistant-exchange-calendar#1]
Hi,
Can you help me to debug this HA custom component.
I get this in HA’s log
``` Logger: exchangelib.account
Source: /usr/local/share/homeassistant/lib/python3.9/site-packages/exchangelib/account.py:105 
First occurred: 09:15:20 (1 occurrences) 
Last logged: 09:15:20

No time zone found with key local. Fallback to UTC 
```
Nothing else but my exchange calendar isn’t showing.
Thanks

**Comment by maxlaverse** [comment]
Hi @tebra-jl ! Have you already read this ? https://stackoverflow.com/questions/67711882/exchangelib-and-pyinstaller-zoneinfo-tzdata-utc-issue
