### ISSUE TITLE
New Version with some LLM support

### ISSUE THREAD

**Issue by oaonder** [maxlaverse/home-assistant-exchange-calendar#3]
hi,

I was looking for a version that will work,

here is one,

#Support for Exchange Calendar.
from __future__ import annotations
from datetime import datetime, timedelta

import logging
import re

import voluptuous as vol

from homeassistant.components.calendar import (
    ENTITY_ID_FORMAT,
    PLATFORM_SCHEMA,
    CalendarEvent,
    CalendarEntity,
    get_date,
    extract_offset,
    is_offset_reached,
)
from homeassistant.const import (
    CONF_NAME,
    CONF_PASSWORD,
    CONF_USERNAME,
    CONF_VERIFY_SSL,
)

from homeassistant.core import HomeAssistant
import homeassistant.helpers.config_validation as cv
from homeassistant.helpers.entity import generate_entity_id
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.typing import ConfigType, DiscoveryInfoType
from homeassistant.util import Throttle, dt

from exchangelib.winzone import MS_TIMEZONE_TO_IANA_MAP
from exchangelib import EWSDateTime, EWSDate, Credentials, Account, Configuration, DELEGATE, EWSTimeZone

# Add a custom entry into the timezone translation map
MS_TIMEZONE_TO_IANA_MAP[''] = "Europe/Istanbul"  # Replace with a reasonable value from CLDR_TO_MS_TIMEZONE_MAP.keys()

_LOGGER = logging.getLogger(__name__)

CONF_CALENDARS = "calendars"
CONF_SEARCH = "search"
CONF_SERVER = "server"
CONF_EMAIL = "email"

OFFSET = "!!"

PLATFORM_SCHEMA = PLATFORM_SCHEMA.extend(
    {
        vol.Required(CONF_SERVER): cv.string,
        vol.Required(CONF_EMAIL): cv.string,
        vol.Inclusive(CONF_USERNAME, "authentication"): cv.string,
        vol.Inclusive(CONF_PASSWORD, "authentication"): cv.string,
        vol.Optional(CONF_CALENDARS, default=[]): vol.All(
            cv.ensure_list,
            [
                vol.Schema(
                    {
                        vol.Required(CONF_NAME): cv.string,
                        vol.Required(CONF_SEARCH): cv.string,
                    }
                )
            ],
        ),
        vol.Optional(CONF_VERIFY_SSL, default=False): cv.boolean,
    }
)

MIN_TIME_BETWEEN_UPDATES = timedelta(minutes=15)

def setup_platform(
    hass: HomeAssistant,
    config: ConfigType,
    add_entities: AddEntitiesCallback,
    disc_info: DiscoveryInfoType | None = None,
) -> None:
    ###Set up the Exchange Calendar platform.
    _LOGGER.warning("Setting up Exchange Calendar platform.")

    server = config[CONF_SERVER]
    email = config.get(CONF_EMAIL)
    username = config.get(CONF_USERNAME)
    password = config.get(CONF_PASSWORD)

    _LOGGER.warning(f"Configuration: server={server}, email={email}, username={username}")

    creds = Credentials(username=username, password=password)
    exconfig = Configuration(server=server, credentials=creds)
    account = Account(primary_smtp_address=email, config=exconfig, autodiscover=False, access_type=DELEGATE)

    _LOGGER.warning(f"Account setup successful: {account.primary_smtp_address}")

    calendar = account.calendar

    calendar_devices = []

    # Create additional calendars based on custom filtering rules
    for cust_calendar in config[CONF_CALENDARS]:
        name = cust_calendar[CONF_NAME]
        device_id = cust_calendar[CONF_NAME]
        entity_id = generate_entity_id(ENTITY_ID_FORMAT, device_id, hass=hass)
        _LOGGER.warning(f"Creating calendar entity: {name}")
        calendar_devices.append(
            ExchangeCalendarEntity(
                name, calendar, entity_id, True, cust_calendar[CONF_SEARCH]
            )
        )

    add_entities(calendar_devices, True)
    _LOGGER.warning("Entities added successfully.")

def convert_to_ewsdatetime(dt_obj, timezone):
    ###Convert a datetime object to EWSDateTime with correct timezone.###
    _LOGGER.warning(f"Converting to EWSDateTime: Type of dt_obj: {type(dt_obj)}, value: {dt_obj}")
    
    if isinstance(dt_obj, EWSDateTime):
        _LOGGER.warning("dt_obj is already EWSDateTime, returning directly.")
        return dt_obj  # Return directly if it's already EWSDateTime
    
    if not isinstance(dt_obj, datetime):
        raise TypeError(f"Expected datetime object, got {type(dt_obj)}")
    
    if dt_obj.tzinfo is None:
        _LOGGER.warning("dt_obj has no tzinfo, replacing with timezone.")
        dt_obj = dt_obj.replace(tzinfo=timezone)
    elif dt_obj.tzinfo != timezone:
        _LOGGER.warning("dt_obj tzinfo is different from timezone, converting to timezone.")
        dt_obj = dt_obj.astimezone(timezone)
    
    # Convert to EWSDateTime using the constructor directly
    _LOGGER.warning("Converting dt_obj to EWSDateTime using constructor.")
    ews_dt = EWSDateTime(dt_obj.year, dt_obj.month, dt_obj.day, dt_obj.hour, dt_obj.minute, dt_obj.second, tzinfo=timezone)
    _LOGGER.warning(f"Converted to EWSDateTime: {ews_dt}")
    return ews_dt

class ExchangeCalendarEntity(CalendarEntity):
    ###A device for getting the next Task from a Exchange Calendar.###

    def __init__(self, name, calendar, entity_id, all_day=False, search=None):
        ###Create the Exchange Calendar Event Device.###
        _LOGGER.warning(f"Initializing ExchangeCalendarEntity: {name}")
        self.data = ExchangeCalendarData(calendar, all_day, search)
        self.entity_id = entity_id
        self._event: CalendarEvent | None = None
        self._attr_name = name

    @property
    def event(self) -> CalendarEvent | None:
        ###Return the next upcoming event.###
        return self._event

    @property
    def name(self):
        ###Return the name of the entity.###
        return self._attr_name

    async def async_get_events(self, hass: HomeAssistant, start_date: datetime, end_date: datetime) -> list[CalendarEvent]:
        ###Get all events in a specific time frame.###
        _LOGGER.warning(f"Getting events for {self._attr_name} from {start_date} to {end_date}")
        return await self.data.async_get_events(hass, start_date, end_date)

    def update(self):
        ###Update event data.###
        _LOGGER.warning(f"Updating event data for {self._attr_name}")
        self.data.update()
        self._event = self.data.event
        if self._event is None:
            return
        self._attr_extra_state_attributes = {
            "offset_reached": is_offset_reached(
                self._event.start_datetime_local, self.data.offset
            )
            if self._event
            else False
        }

class ExchangeCalendarData:
    ###Class to utilize the calendar dav client object to get next event.###

    def __init__(self, calendar, include_all_day, search):
        ###Set up how we are going to search the Exchange calendar.###
        _LOGGER.warning("Initializing ExchangeCalendarData.")
        self.calendar = calendar
        self.include_all_day = include_all_day
        self.search = search
        self.event = None
        self.offset = None

    async def async_get_events(self, hass: HomeAssistant, start_date: datetime, end_date: datetime):
        ###Get all events in a specific time frame.###
        _LOGGER.warning(f"Fetching events from {start_date} to {end_date}")
        return await hass.async_add_executor_job(self._fetch_events, start_date, end_date)

    def _fetch_events(self, start_date: datetime, end_date: datetime):
        ###Fetch events from Exchange calendar.###
        _LOGGER.warning("Executing _fetch_events.")
        vevent_list = self.calendar.view(
            start=convert_to_ewsdatetime(start_date, self.calendar.account.default_timezone),
            end=convert_to_ewsdatetime(end_date, self.calendar.account.default_timezone)
        ).order_by('start')
        event_list = []
        for vevent in vevent_list:
            # _LOGGER.warning(f"Fetched event: {vevent.subject} from {vevent.start} to {vevent.end}")
            event_list.append(
                CalendarEvent(
                    summary=vevent.subject,
                    start=vevent.start.isoformat(),
                    end=vevent.end.isoformat(),
                    location=vevent.location,
                    description=vevent.text_body,
                )
            )
        _LOGGER.warning(f"Fetched {len(event_list)} events.")
        return event_list

    @Throttle(MIN_TIME_BETWEEN_UPDATES)
    def update(self):
        ###Get the latest data.###
        _LOGGER.warning("Updating calendar data.")
        timezone = self.calendar.account.default_timezone
        now = dt.now(timezone)
        future_date = now + timedelta(days=15)
        
        results = self.calendar.filter(
            start__lt=convert_to_ewsdatetime(future_date, timezone),
            end__gt=convert_to_ewsdatetime(now, timezone)
        )

        for event in results:
            _LOGGER.warning(f"Event found: {event.subject} from {event.start} to {event.end}")

        if not results:
            _LOGGER.warning(
                "No matching event found in the %d results for %s",
                results.count(),
                self.calendar.name,
            )
            self.event = None
            return

        vevent = next(
            (
                event
                for event in results
                if (
                    self.is_matching(event, self.search)
                    and (
                        not event.is_all_day
                        or self.include_all_day
                    )
                    and not self.is_over(event)
                )
            ),
            None,
        )

        if vevent is None:
            _LOGGER.warning(
                "No matching event found in the %d results for %s",
                results.count(),
                self.calendar.name,
            )
            self.event = None
            return

        (summary, offset) = extract_offset(vevent.subject, OFFSET)
        
        # Ensure start and end times have timezone information
        start_time = self._convert_to_datetime(vevent.start)
        end_time = self._convert_to_datetime(vevent.end)
        
        _LOGGER.warning(f"Start time: {start_time}, Type: {type(start_time)}, tzinfo: {getattr(start_time, 'tzinfo', None)}")
        _LOGGER.warning(f"End time: {end_time}, Type: {type(end_time)}, tzinfo: {getattr(end_time, 'tzinfo', None)}")
        
        self.event = CalendarEvent(
            start=start_time,
            end=end_time,
            summary=summary,
            location=vevent.location,
            description=vevent.text_body,
        )
        self.offset = offset
        _LOGGER.warning(f"Found event: {self.event}")

    @staticmethod
    def _convert_to_datetime(date):
        ###Convert EWSDateTime or EWSDate to datetime.###
        if isinstance(date, EWSDateTime):
            return date.astimezone(date.tzinfo)  # Ensure timezone is included
        if isinstance(date, EWSDate):
            return datetime.combine(date, datetime.min.time())  # No timezone for all-day events
        return date

    @staticmethod
    def is_matching(event, search):
        ###Return if the event matches the filter criteria.###
        if search is None:
            return True

        pattern = re.compile(search)
        return (
            hasattr(event, "subject")
            and event.subject is not None
            and pattern.match(event.subject)
            or hasattr(event, "location")
            and event.location is not None
            and pattern.match(event.location)
            or hasattr(event, "text_body")
            and event.text_body is not None
            and pattern.match(event.text_body)
        )

    @staticmethod
    def is_over(event):
        ###Return if the event is over.###
        if isinstance(event.end, EWSDateTime):
            return dt.now() >= event.end

        return EWSDate.from_date(dt.now().date()) >= event.end

**Comment by maxlaverse** [comment]
Hi @oaonder 
I'll archive this repository as I don't have time to maintain it, and decided to stop using the component a while ago.
It's still accessible publicly, which means you should be able to fork it if you'd decide to maintain your own version of it.
Best
